### ISSUE TITLE
KeyError: 'dmenu'

### ISSUE THREAD

**Issue by arkhan** [firecat53/nmcli-dmenu#15]
I have this error when try to connect new wifi

```bash
arkhan@Pantheon ~ % /usr/bin/nmcli_dmenu
/usr/bin/nmcli_dmenuTraceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'dmenu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nmcli_dmenu", line 370, in <module>
    run()
  File "/usr/bin/nmcli_dmenu", line 363, in run
    pw = get_passphrase()
  File "/usr/bin/nmcli_dmenu", line 295, in get_passphrase
    pinentry = conf.get("dmenu", "pinentry")
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'dmenu'
```
Thanks

**Comment by firecat53** [comment]
That should do it! Thanks for finding that :)
